# Generated by Django 4.2.1 on 2023-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('friend', models.CharField(max_length=40)),
                ('last_update', models.DateField()),
            ],
        ),
    ]
